version: '3'
services:
  jeanlouis-react:
    container_name: jeanlouis-react
    build: .
    working_dir: /app
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
    volumes:
      - ./:/app
    command: "npm start"
