name: Deploy staging branch
on:
  push:
    branches:
      - deploy-staging
# jobs:
#   Deploy-Staging-Branch:
#     runs-on: ubuntu-latest
#     steps:
    
#       - name: Install SSH key
#         uses: shimataro/ssh-key-action@v2
#         with:
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
#       - name: Adding Known Hosts
#         run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
#       - name: Deploy with rsync
#         run: rsync -avz ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/test/
#       - run: echo "🍏 This job's status is ${{ job.status }}."
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --delete
        path: ./
        remote_path: /var/www/test/
        remote_host: ${{ secrets.SSH_HOST }}
        remote_user: ${{ secrets.SSH_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
